spring:
  datasource:
    url: jdbc:mysql://localhost/weatherdb
    username: chris
    password: Chris@24
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    
logging:
  file:
    path: /resources
    file: mylogs.log
    
    
    
    