spring: 
  datasource:
    url: jdbc:mysql://localhost/weatherdb
    username: root
    password: chris
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
      
